
language: java

matrix:
  include:
    - os: linux
      jdk: openjdk6
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: oraclejdk8
    - os: osx

os:
  - linux
  - osx

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
