
language: java

matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: linux
      jdk: openjdk6
      before_install:
        - jdk_switcher use openjdk6
    - os: linux
      jdk: openjdk7
      before_install:
        - jdk_switcher use openjdk7
    - os: linux
      jdk: oraclejdk7
      before_install:
        - jdk_switcher use oraclejdk7
    - os: linux
      jdk: oraclejdk8
      before_install:
        - jdk_switcher use oraclejdk8

install: true

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
